#!/bin/bash

#SBATCH --job-name=test-cbis    # Job name
#SBATCH --output=run_test_inbreast.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu              # Schedule a GPU # gres=gpu #gpu:a30:1
#SBATCH --exclude=desktop[17-18]    
## SBATCH --exclude=desktop[17-18],desktop[1-10]      
#SBATCH --mem-per-cpu=800    # Memory per core
#SBATCH --time=03:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown    # Run on either the red or brown queue

module purge

# Avoid GPU
#export CUDA_VISIBLE_DEVICES=-1

module load Python/3.7.4-GCCcore-8.3.0
module load TensorFlow/1.15.2-fosscuda-2019b-Python-3.7.4
module load Pillow/6.2.1-GCCcore-8.3.0
module load scikit-learn/0.21.3-foss-2019b-Python-3.7.4
#module load cuDNN/7.4.2.24-CUDA-10.0.130

VENVNAME="venv1"

source $HOME/bsc/venvs/$VENVNAME/bin/activate

echo $HOME/bsc/venvs/$VENVNAME/bin/activate


python test_inbreast.py